// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO auth_sessions(id, email, password_hash)
VALUES($1, $2, $3)
`

type CreateSessionParams struct {
	ID           string
	Email        string
	PasswordHash string
}

// Create User
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.ID, arg.Email, arg.PasswordHash)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM auth_sessions
WHERE id = $1
`

// Delete User Account
func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const findAllSessions = `-- name: FindAllSessions :many
SELECT id, user_id, email, password_hash, is_active, created_at, updated_at
FROM auth_sessions
ORDER BY created_at DESC
`

// Get All Users With Data
func (q *Queries) FindAllSessions(ctx context.Context) ([]AuthSession, error) {
	rows, err := q.db.Query(ctx, findAllSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthSession
	for rows.Next() {
		var i AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.PasswordHash,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOneSession = `-- name: FindOneSession :one
SELECT id, user_id, email, password_hash, is_active, created_at, updated_at
FROM auth_sessions
WHERE id = $1
`

// Get User Data
func (q *Queries) FindOneSession(ctx context.Context, id string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, findOneSession, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOneSessionByEmail = `-- name: FindOneSessionByEmail :one
SELECT id, user_id, email, password_hash, is_active, created_at, updated_at
FROM auth_sessions
WHERE email = $1
`

// Get User Data By Email
func (q *Queries) FindOneSessionByEmail(ctx context.Context, email string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, findOneSessionByEmail, email)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const toggleDeactivateSession = `-- name: ToggleDeactivateSession :exec
UPDATE auth_sessions
SET is_active = COALESCE($1, is_active)
WHERE id = $1
`

// Toggle Deactivate User Account
func (q *Queries) ToggleDeactivateSession(ctx context.Context, isActive pgtype.Int4) error {
	_, err := q.db.Exec(ctx, toggleDeactivateSession, isActive)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE auth_sessions
SET password_hash = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           string
	PasswordHash string
}

// Update User Date
func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}
