// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Guild struct {
	ID         string
	GuildName  string
	InviteLink pgtype.Text
}

type Message struct {
	ID      string
	Content string
}

type User struct {
	ID           string
	Email        string
	Username     pgtype.Text
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type UserGuild struct {
	UserID   string
	GuildID  string
	Role     pgtype.Text
	JoinedAt pgtype.Timestamp
}
