// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	ID           string
	UserID       string
	Email        string
	PasswordHash string
	IsActive     pgtype.Int4
	CreatedAt    interface{}
	UpdatedAt    interface{}
}

type Guild struct {
	ID         string
	GuildName  string
	InviteLink pgtype.Text
}

type Message struct {
	ID      string
	Content string
}

type User struct {
	ID                string
	Username          pgtype.Text
	DisplayName       pgtype.Text
	AccountStatus     string
	UsernameChangedAt interface{}
	CreatedAt         interface{}
	UpdatedAt         interface{}
	DeletedAt         interface{}
	DeletedAfter      pgtype.Int4
}

type UserGuild struct {
	UserID   string
	GuildID  string
	Role     pgtype.Text
	JoinedAt interface{}
}
