// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users(id,email,password_hash) VALUES($1,$2,$3)
`

type CreateUserParams struct {
	ID           string
	Email        string
	PasswordHash string
}

// Create User
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.ID, arg.Email, arg.PasswordHash)
	return err
}

const deleteUser = `-- name: DeleteUser :exec



DELETE FROM users WHERE id = $1
`

// Update User Date
// Update Profile Picture
// Delete User Account
func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const findAllUsers = `-- name: FindAllUsers :many
SELECT id, email, username, password_hash, created_at, updated_at FROM users ORDER BY created_at DESC
`

// Get All Users With Data
func (q *Queries) FindAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, findAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOneUser = `-- name: FindOneUser :one
SELECT id, email, username, password_hash, created_at, updated_at FROM users WHERE id = $1
`

// Get User Data
func (q *Queries) FindOneUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, findOneUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOneUserByEmail = `-- name: FindOneUserByEmail :one
SELECT id, email, username, password_hash, created_at, updated_at FROM users WHERE email = $1
`

// Get User Data By Email
func (q *Queries) FindOneUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findOneUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
